### ISSUE TITLE
Incorrect use statements for PHPDocs

### ISSUE THREAD

**Issue by nialltiernan** [dimuska139/rawg-sdk-php#1]
Hi Dmitriy,

I found a small issue in GenresResource and DevelopersResource where

`use Rawg\Exceptions\ApiException;`

uses the wrong path. It should be

`use Rawg\ApiException;`.

Otherwise the code is really nice, thanks for making it!

**Comment by dimuska139** [comment]
@nialltiernan thank you for the issue and for the compliment! Yes, it uses the wrong path. I've fixed it: https://github.com/dimuska139/rawg-sdk-php/commit/ed1dd9c99d96c815e941996f9ddce35eb2d452de
